import { Children, cloneElement, createContext, isValidElement, useContext, useEffect, useMemo, useState } from 'react'

export const LANGUAGES = [
  { code: 'en', label: 'English', nativeLabel: 'English' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी' },
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা' },
  { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்' },
]

const translations = {
  en: {
    overview: 'Overview',
    courseCatalog: 'Course catalog',
    people: 'People',
    announcements: 'Announcements',
    certificates: 'Certificates',
    mentor: 'IMD AI mentor',
    competencyMap: 'Competency Compass',
    profile: 'My profile',
    verify: 'Verify certificate',
    trainee: 'Trainee',
    trainer: 'Trainer',
    admin: 'Admin',
    signOut: 'Sign out',
    language: 'Language',
    mentorTitle: 'IMD AI mentor',
    mentorSubtitle: 'A flexible learning companion for meteorology, technology, professional development, and your Capacity Connect courses.',
    askMentor: 'Ask the mentor',
    mentorHint: 'Ask in any supported language. The mentor replies in your language.',
    mentorThinking: 'The mentor is thinking…',
    send: 'Send',
    mentorPlaceholder: 'Ask anything or explore a topic…',
    tryAsking: 'Try asking',
    learningContext: 'Your learning context',
    noCourses: 'No enrolled courses yet.',
    goodUseCases: 'Good use cases',
    goodUseCasesText: 'Use it to explore an IMD project, learn a new concept, review code or data, prepare a briefing, practise an oral examination, or discuss another professional topic.',
    focus: 'Flexible learning',
    noResponse: 'I could not generate a response.',
    loading: 'Loading…',
    text: {},
    firstMessage: (name) => `Hello ${name}! I am your IMD AI Mentor. Ask me about meteorology, technology, career development, your courses, or any other topic where a learning companion can help.`,
  },
  hi: {
    overview: 'अवलोकन',
    courseCatalog: 'पाठ्यक्रम सूची',
    people: 'लोग',
    announcements: 'घोषणाएँ',
    certificates: 'प्रमाणपत्र',
    mentor: 'IMD AI मेंटर',
    competencyMap: 'कौशल मानचित्र',
    profile: 'मेरी प्रोफ़ाइल',
    verify: 'प्रमाणपत्र सत्यापित करें',
    trainee: 'प्रशिक्षु',
    trainer: 'प्रशिक्षक',
    admin: 'व्यवस्थापक',
    signOut: 'साइन आउट',
    language: 'भाषा',
    mentorTitle: 'IMD AI मेंटर',
    mentorSubtitle: 'मौसम विज्ञान, तकनीक, पेशेवर विकास और आपके Capacity Connect पाठ्यक्रमों के लिए एक लचीला अध्ययन साथी।',
    askMentor: 'मेंटर से पूछें',
    mentorHint: 'किसी भी समर्थित भाषा में पूछें। मेंटर आपकी भाषा में उत्तर देगा।',
    mentorThinking: 'मेंटर सोच रहा है…',
    send: 'भेजें',
    mentorPlaceholder: 'कुछ भी पूछें या कोई विषय explore करें…',
    tryAsking: 'यह पूछकर देखें',
    learningContext: 'आपका अध्ययन संदर्भ',
    noCourses: 'अभी कोई पाठ्यक्रम नहीं है।',
    goodUseCases: 'उपयोग के तरीके',
    goodUseCasesText: 'IMD प्रोजेक्ट, नई अवधारणा, कोड या डेटा, ब्रीफिंग और मौखिक परीक्षा की तैयारी के लिए इसका उपयोग करें। आप अन्य पेशेवर विषयों पर भी चर्चा कर सकते हैं।',
    focus: 'लचीला अध्ययन',
    noResponse: 'उत्तर तैयार नहीं हो सका।',
    loading: 'लोड हो रहा है…',
    text: {
      'Welcome back': 'वापसी पर स्वागत है',
      'Sign in to continue your training.': 'अपना प्रशिक्षण जारी रखने के लिए साइन इन करें।',
      'Sign in': 'साइन इन',
      'Create an account': 'खाता बनाएँ',
      'Verify it publicly': 'सार्वजनिक रूप से सत्यापित करें',
      'Create your account': 'अपना खाता बनाएँ',
      'Get approved, then start training.': 'अनुमोदन प्राप्त करें और प्रशिक्षण शुरू करें।',
      'Account created': 'खाता बन गया',
      'My profile': 'मेरी प्रोफ़ाइल',
      'Course catalog': 'पाठ्यक्रम सूची',
      'My courses': 'मेरे पाठ्यक्रम',
      'Admin overview': 'व्यवस्थापक अवलोकन',
      'Organization-wide training status at a glance.': 'पूरे संगठन की प्रशिक्षण स्थिति एक नज़र में।',
      'Your courses': 'आपके पाठ्यक्रम',
      'Announcements': 'घोषणाएँ',
      'No courses yet': 'अभी कोई पाठ्यक्रम नहीं है',
      'Browse courses': 'पाठ्यक्रम देखें',
      'Browse catalog →': 'कैटलॉग देखें →',
      'Continue': 'जारी रखें',
      'Nothing posted yet': 'अभी कुछ पोस्ट नहीं किया गया',
      'No certificates yet': 'अभी कोई प्रमाणपत्र नहीं है',
      'View': 'देखें',
      'Enroll': 'नामांकन करें',
      'Enrolling…': 'नामांकन हो रहा है…',
      'Search courses…': 'पाठ्यक्रम खोजें…',
      'All categories': 'सभी श्रेणियाँ',
      'No courses found': 'कोई पाठ्यक्रम नहीं मिला',
      'Learning material': 'अध्ययन सामग्री',
      'Tests': 'परीक्षण',
      'Passed': 'उत्तीर्ण',
      'Start': 'शुरू करें',
      'Submit test': 'परीक्षण जमा करें',
      'Next question': 'अगला प्रश्न',
      'Save changes': 'बदलाव सहेजें',
      'Saving…': 'सहेजा जा रहा है…',
      'Saved ✓': 'सहेजा गया ✓',
      'Download PDF': 'PDF डाउनलोड करें',
      'Verify': 'सत्यापित करें',
      'Approve': 'अनुमोदित करें',
      'Reject': 'अस्वीकार करें',
      'People': 'लोग',
      'Courses': 'पाठ्यक्रम',
      'Trainers': 'प्रशिक्षक',
      'Trainees': 'प्रशिक्षु',
      'Certificates issued': 'जारी प्रमाणपत्र',
      'Pending approvals': 'लंबित अनुमोदन',
      'Approve sign-ups, manage roles.': 'साइन-अप अनुमोदित करें और भूमिकाएँ प्रबंधित करें।',
      'Post announcement': 'घोषणा पोस्ट करें',
      'Remove': 'हटाएँ',
      'Publish': 'प्रकाशित करें',
      'Unpublish': 'प्रकाशन हटाएँ',
      'Manage': 'प्रबंधित करें',
      'Open': 'खोलें',
      'Create a course': 'पाठ्यक्रम बनाएँ',
      'New course': 'नया पाठ्यक्रम',
      'Cancel': 'रद्द करें',
      'Create course': 'पाठ्यक्रम बनाएँ',
      'Creating…': 'बनाया जा रहा है…',
      'Loading…': 'लोड हो रहा है…',
    },
    firstMessage: (name) => `नमस्ते ${name}! मैं आपका IMD AI मेंटर हूँ। मौसम विज्ञान, तकनीक, करियर विकास, आपके पाठ्यक्रम या किसी भी सीखने से जुड़े विषय के बारे में पूछें।`,
  },
  bn: {
    overview: 'সারাংশ',
    courseCatalog: 'কোর্স ক্যাটালগ',
    people: 'ব্যবহারকারীরা',
    announcements: 'ঘোষণা',
    certificates: 'সার্টিফিকেট',
    mentor: 'IMD AI মেন্টর',
    competencyMap: 'দক্ষতা মানচিত্র',
    profile: 'আমার প্রোফাইল',
    verify: 'সার্টিফিকেট যাচাই করুন',
    trainee: 'প্রশিক্ষণার্থী',
    trainer: 'প্রশিক্ষক',
    admin: 'অ্যাডমিন',
    signOut: 'সাইন আউট',
    language: 'ভাষা',
    mentorTitle: 'IMD AI মেন্টর',
    mentorSubtitle: 'আবহাওয়াবিদ্যা, প্রযুক্তি, পেশাগত উন্নতি এবং আপনার Capacity Connect কোর্সের জন্য একটি নমনীয় শেখার সঙ্গী।',
    askMentor: 'মেন্টরকে জিজ্ঞাসা করুন',
    mentorHint: 'যে কোনো সমর্থিত ভাষায় জিজ্ঞাসা করুন। মেন্টর আপনার ভাষায় উত্তর দেবে।',
    mentorThinking: 'মেন্টর ভাবছে…',
    send: 'পাঠান',
    mentorPlaceholder: 'যেকোনো প্রশ্ন করুন বা কোনো বিষয় অনুসন্ধান করুন…',
    tryAsking: 'এগুলো জিজ্ঞাসা করে দেখুন',
    learningContext: 'আপনার শেখার প্রসঙ্গ',
    noCourses: 'এখনও কোনো কোর্সে ভর্তি হননি।',
    goodUseCases: 'ব্যবহারের উদাহরণ',
    goodUseCasesText: 'IMD প্রকল্প, নতুন ধারণা, কোড বা ডেটা, ব্রিফিং এবং মৌখিক পরীক্ষার প্রস্তুতিতে এটি ব্যবহার করুন। অন্যান্য পেশাগত বিষয় নিয়েও আলোচনা করতে পারেন।',
    focus: 'নমনীয় শিক্ষা',
    noResponse: 'উত্তর তৈরি করা যায়নি।',
    loading: 'লোড হচ্ছে…',
    text: {
      'Welcome back': 'আবার স্বাগতম',
      'Sign in': 'সাইন ইন',
      'Create an account': 'অ্যাকাউন্ট তৈরি করুন',
      'Create your account': 'আপনার অ্যাকাউন্ট তৈরি করুন',
      'Account created': 'অ্যাকাউন্ট তৈরি হয়েছে',
      'Course catalog': 'কোর্স ক্যাটালগ',
      'My courses': 'আমার কোর্স',
      'Admin overview': 'অ্যাডমিন সারাংশ',
      'Your courses': 'আপনার কোর্স',
      'Announcements': 'ঘোষণা',
      'No courses yet': 'এখনও কোনো কোর্স নেই',
      'Browse courses': 'কোর্স দেখুন',
      'Continue': 'চালিয়ে যান',
      'Nothing posted yet': 'এখনও কিছু পোস্ট করা হয়নি',
      'No certificates yet': 'এখনও কোনো সার্টিফিকেট নেই',
      'View': 'দেখুন',
      'Enroll': 'ভর্তি হন',
      'Enrolling…': 'ভর্তি হচ্ছে…',
      'Search courses…': 'কোর্স খুঁজুন…',
      'All categories': 'সব বিভাগ',
      'No courses found': 'কোনো কোর্স পাওয়া যায়নি',
      'Learning material': 'শেখার উপকরণ',
      'Tests': 'পরীক্ষা',
      'Passed': 'পাস',
      'Start': 'শুরু করুন',
      'Submit test': 'পরীক্ষা জমা দিন',
      'Next question': 'পরের প্রশ্ন',
      'Save changes': 'পরিবর্তন সংরক্ষণ করুন',
      'Saving…': 'সংরক্ষণ হচ্ছে…',
      'Saved ✓': 'সংরক্ষিত ✓',
      'Download PDF': 'PDF ডাউনলোড করুন',
      'Verify': 'যাচাই করুন',
      'Approve': 'অনুমোদন',
      'Reject': 'প্রত্যাখ্যান',
      'People': 'ব্যবহারকারীরা',
      'Courses': 'কোর্স',
      'Trainers': 'প্রশিক্ষক',
      'Trainees': 'প্রশিক্ষণার্থী',
      'Certificates issued': 'জারি করা সার্টিফিকেট',
      'Pending approvals': 'অনুমোদনের অপেক্ষায়',
      'Post announcement': 'ঘোষণা পোস্ট করুন',
      'Remove': 'মুছুন',
      'Publish': 'প্রকাশ করুন',
      'Unpublish': 'প্রকাশনা সরান',
      'Manage': 'পরিচালনা করুন',
      'Open': 'খুলুন',
      'Create a course': 'কোর্স তৈরি করুন',
      'New course': 'নতুন কোর্স',
      'Cancel': 'বাতিল',
      'Create course': 'কোর্স তৈরি করুন',
      'Creating…': 'তৈরি হচ্ছে…',
    },
    firstMessage: (name) => `নমস্কার ${name}! আমি আপনার IMD AI মেন্টর। আবহাওয়াবিদ্যা, প্রযুক্তি, ক্যারিয়ার উন্নতি, আপনার কোর্স বা অন্য কোনো শেখার বিষয় নিয়ে প্রশ্ন করুন।`,
  },
  mr: {
    overview: 'आढावा',
    courseCatalog: 'अभ्यासक्रम',
    people: 'लोक',
    announcements: 'सूचना',
    certificates: 'प्रमाणपत्रे',
    mentor: 'IMD AI मार्गदर्शक',
    competencyMap: 'कौशल्य नकाशा',
    profile: 'माझे प्रोफाइल',
    verify: 'प्रमाणपत्र तपासा',
    trainee: 'प्रशिक्षणार्थी',
    trainer: 'प्रशिक्षक',
    admin: 'प्रशासक',
    signOut: 'साइन आउट',
    language: 'भाषा',
    mentorTitle: 'IMD AI मार्गदर्शक',
    mentorSubtitle: 'हवामानशास्त्र, तंत्रज्ञान, व्यावसायिक विकास आणि Capacity Connect अभ्यासक्रमांसाठी लवचिक शिकण्याचा साथीदार।',
    askMentor: 'मार्गदर्शकाला विचारा',
    mentorHint: 'कोणत्याही समर्थित भाषेत विचारा. मार्गदर्शक तुमच्या भाषेत उत्तर देईल.',
    mentorThinking: 'मार्गदर्शक विचार करत आहे…',
    send: 'पाठवा',
    mentorPlaceholder: 'काहीही विचारा किंवा एखादा विषय शोधा…',
    tryAsking: 'हे विचारून पहा',
    learningContext: 'तुमचा शिकण्याचा संदर्भ',
    noCourses: 'अद्याप कोणताही अभ्यासक्रम नाही.',
    goodUseCases: 'उपयोग',
    goodUseCasesText: 'IMD प्रकल्प, नवीन संकल्पना, कोड किंवा डेटा, ब्रीफिंग आणि तोंडी परीक्षेच्या तयारीसाठी याचा वापर करा. इतर व्यावसायिक विषयांवरही चर्चा करू शकता.',
    focus: 'लवचिक शिक्षण',
    noResponse: 'उत्तर तयार करता आले नाही.',
    loading: 'लोड होत आहे…',
    text: {
      'Welcome back': 'पुन्हा स्वागत आहे',
      'Sign in': 'साइन इन',
      'Create an account': 'खाते तयार करा',
      'Create your account': 'तुमचे खाते तयार करा',
      'Account created': 'खाते तयार झाले',
      'Course catalog': 'अभ्यासक्रम',
      'My courses': 'माझे अभ्यासक्रम',
      'Admin overview': 'प्रशासकीय आढावा',
      'Your courses': 'तुमचे अभ्यासक्रम',
      'Announcements': 'सूचना',
      'No courses yet': 'अद्याप अभ्यासक्रम नाहीत',
      'Browse courses': 'अभ्यासक्रम पहा',
      'Continue': 'पुढे जा',
      'Nothing posted yet': 'अद्याप काहीही पोस्ट केलेले नाही',
      'No certificates yet': 'अद्याप प्रमाणपत्रे नाहीत',
      'View': 'पहा',
      'Enroll': 'नोंदणी करा',
      'Enrolling…': 'नोंदणी होत आहे…',
      'Search courses…': 'अभ्यासक्रम शोधा…',
      'All categories': 'सर्व श्रेणी',
      'No courses found': 'अभ्यासक्रम सापडले नाहीत',
      'Learning material': 'अभ्यास साहित्य',
      'Tests': 'चाचण्या',
      'Passed': 'उत्तीर्ण',
      'Start': 'सुरू करा',
      'Submit test': 'चाचणी सबमिट करा',
      'Next question': 'पुढील प्रश्न',
      'Save changes': 'बदल जतन करा',
      'Saving…': 'जतन होत आहे…',
      'Saved ✓': 'जतन केले ✓',
      'Download PDF': 'PDF डाउनलोड करा',
      'Verify': 'तपासा',
      'Approve': 'मंजूर करा',
      'Reject': 'नाकारा',
      'People': 'लोक',
      'Courses': 'अभ्यासक्रम',
      'Trainers': 'प्रशिक्षक',
      'Trainees': 'प्रशिक्षणार्थी',
      'Certificates issued': 'जारी केलेली प्रमाणपत्रे',
      'Pending approvals': 'प्रलंबित मंजुरी',
      'Post announcement': 'सूचना पोस्ट करा',
      'Remove': 'काढा',
      'Publish': 'प्रकाशित करा',
      'Unpublish': 'प्रकाशन काढा',
      'Manage': 'व्यवस्थापित करा',
      'Open': 'उघडा',
      'Create a course': 'अभ्यासक्रम तयार करा',
      'New course': 'नवीन अभ्यासक्रम',
      'Cancel': 'रद्द करा',
      'Create course': 'अभ्यासक्रम तयार करा',
      'Creating…': 'तयार होत आहे…',
    },
    firstMessage: (name) => `नमस्कार ${name}! मी तुमचा IMD AI मार्गदर्शक आहे. हवामानशास्त्र, तंत्रज्ञान, करिअर विकास, अभ्यासक्रम किंवा इतर कोणत्याही शिकण्याच्या विषयाबद्दल विचारा.`,
  },
  ta: {
    overview: 'கண்ணோட்டம்',
    courseCatalog: 'பாடநெறி பட்டியல்',
    people: 'பயனர்கள்',
    announcements: 'அறிவிப்புகள்',
    certificates: 'சான்றிதழ்கள்',
    mentor: 'IMD AI வழிகாட்டி',
    competencyMap: 'திறன் வரைபடம்',
    profile: 'என் சுயவிவரம்',
    verify: 'சான்றிதழை சரிபார்க்கவும்',
    trainee: 'பயிற்சியாளர்',
    trainer: 'பயிற்றுநர்',
    admin: 'நிர்வாகி',
    signOut: 'வெளியேறு',
    language: 'மொழி',
    mentorTitle: 'IMD AI வழிகாட்டி',
    mentorSubtitle: 'வானிலை அறிவியல், தொழில்நுட்பம், தொழில் வளர்ச்சி மற்றும் Capacity Connect பாடநெறிகளுக்கான நெகிழ்வான கற்றல் துணை.',
    askMentor: 'வழிகாட்டியிடம் கேளுங்கள்',
    mentorHint: 'ஆதரிக்கப்படும் எந்த மொழியிலும் கேளுங்கள். வழிகாட்டி உங்கள் மொழியில் பதிலளிப்பார்.',
    mentorThinking: 'வழிகாட்டி சிந்திக்கிறார்…',
    send: 'அனுப்பு',
    mentorPlaceholder: 'எதையும் கேளுங்கள் அல்லது ஒரு தலைப்பை ஆராயுங்கள்…',
    tryAsking: 'இவற்றைக் கேட்டு பாருங்கள்',
    learningContext: 'உங்கள் கற்றல் சூழல்',
    noCourses: 'இன்னும் பாடநெறிகள் இல்லை.',
    goodUseCases: 'பயன்பாடுகள்',
    goodUseCasesText: 'IMD திட்டம், புதிய கருத்து, குறியீடு அல்லது தரவு, விளக்கக்காட்சி மற்றும் வாய்மொழித் தேர்வுக்குத் தயாராக இதைப் பயன்படுத்துங்கள். பிற தொழில்முறை தலைப்புகளையும் விவாதிக்கலாம்.',
    focus: 'நெகிழ்வான கற்றல்',
    noResponse: 'பதிலை உருவாக்க முடியவில்லை.',
    loading: 'ஏற்றுகிறது…',
    text: {
      'Welcome back': 'மீண்டும் வரவேற்கிறோம்',
      'Sign in': 'உள்நுழைக',
      'Create an account': 'கணக்கை உருவாக்கவும்',
      'Create your account': 'உங்கள் கணக்கை உருவாக்கவும்',
      'Account created': 'கணக்கு உருவாக்கப்பட்டது',
      'Course catalog': 'பாடநெறி பட்டியல்',
      'My courses': 'என் பாடநெறிகள்',
      'Admin overview': 'நிர்வாக கண்ணோட்டம்',
      'Your courses': 'உங்கள் பாடநெறிகள்',
      'Announcements': 'அறிவிப்புகள்',
      'No courses yet': 'இன்னும் பாடநெறிகள் இல்லை',
      'Browse courses': 'பாடநெறிகளைப் பார்க்கவும்',
      'Continue': 'தொடரவும்',
      'Nothing posted yet': 'இன்னும் எதுவும் பதிவிடப்படவில்லை',
      'No certificates yet': 'இன்னும் சான்றிதழ்கள் இல்லை',
      'View': 'பார்க்கவும்',
      'Enroll': 'சேரவும்',
      'Enrolling…': 'சேர்க்கப்படுகிறது…',
      'Search courses…': 'பாடநெறிகளைத் தேடுங்கள்…',
      'All categories': 'அனைத்து வகைகள்',
      'No courses found': 'பாடநெறிகள் எதுவும் கிடைக்கவில்லை',
      'Learning material': 'கற்றல் பொருள்',
      'Tests': 'சோதனைகள்',
      'Passed': 'தேர்ச்சி',
      'Start': 'தொடங்கு',
      'Submit test': 'சோதனையைச் சமர்ப்பிக்கவும்',
      'Next question': 'அடுத்த கேள்வி',
      'Save changes': 'மாற்றங்களைச் சேமிக்கவும்',
      'Saving…': 'சேமிக்கப்படுகிறது…',
      'Saved ✓': 'சேமிக்கப்பட்டது ✓',
      'Download PDF': 'PDF பதிவிறக்கவும்',
      'Verify': 'சரிபார்க்கவும்',
      'Approve': 'அனுமதிக்கவும்',
      'Reject': 'நிராகரிக்கவும்',
      'People': 'பயனர்கள்',
      'Courses': 'பாடநெறிகள்',
      'Trainers': 'பயிற்றுநர்கள்',
      'Trainees': 'பயிற்சியாளர்கள்',
      'Certificates issued': 'வழங்கப்பட்ட சான்றிதழ்கள்',
      'Pending approvals': 'நிலுவையிலுள்ள அனுமதிகள்',
      'Post announcement': 'அறிவிப்பைப் பதிவிடவும்',
      'Remove': 'நீக்கு',
      'Publish': 'வெளியிடு',
      'Unpublish': 'வெளியீட்டை நீக்கு',
      'Manage': 'நிர்வகிக்கவும்',
      'Open': 'திறக்கவும்',
      'Create a course': 'பாடநெறியை உருவாக்கவும்',
      'New course': 'புதிய பாடநெறி',
      'Cancel': 'ரத்து செய்',
      'Create course': 'பாடநெறியை உருவாக்கவும்',
      'Creating…': 'உருவாக்கப்படுகிறது…',
    },
    firstMessage: (name) => `வணக்கம் ${name}! நான் உங்கள் IMD AI வழிகாட்டி. வானிலை அறிவியல், தொழில்நுட்பம், தொழில் வளர்ச்சி, பாடநெறிகள் அல்லது வேறு எந்த கற்றல் தலைப்பைப் பற்றியும் கேளுங்கள்.`,
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('capacity-connect-language') || 'en')

  useEffect(() => {
    localStorage.setItem('capacity-connect-language', language)
    document.documentElement.lang = language
  }, [language])

  const value = useMemo(() => ({
    language,
    setLanguage,
    languages: LANGUAGES,
    t: translations[language] ?? translations.en,
    translate: (value) => translations[language]?.text?.[value] ?? value,
  }), [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider')
  return context
}

export function LocalizedContent({ children }) {
  const { translate } = useLanguage()

  const localize = (node) => {
    if (typeof node === 'string') return translate(node)
    if (!isValidElement(node)) return node
    return cloneElement(node, {}, Children.map(node.props.children, localize))
  }

  return <>{Children.map(children, localize)}</>
}
